### PR TITLE
fix broken path to Workspace.hpp

### PR DESCRIPTION
**Pull request by bivsk**
Reflects https://github.com/hyprwm/Hyprland/commit/b39dcfa497f84486569bf862092dfcfadbfd8747

### CODE REVIEW

**Comment by jacekpoz** [comment]
running this right now, can confirm it works

**Comment by kofteistkofte** [comment]
This fix works for me too.

**Comment by John-Paul-R** [comment]
Works here too.

This should resolve #53

**Comment by nonetrix** [comment]
Doesn't work for me

**Comment by nonetrix** [comment]
Works for me but now Hyprland is broken I think, likely unrelated

**Comment by iddm** [comment]
Can we merge this? Or at least review? @Duckonaut

**Comment by iddm** [comment]
So this fixed the build issue and now `Hyprland` can load the plugin again, however, this doesn't work and it still associates 1-10 with one monitor and 11-20 with another, while I need 1-5 on one and 6-10 on another:

```
plugin {
    split-monitor-workspaces {
        count = 5
    }
}
```

**Comment by Pico-Dev** [comment]
This should be pulled, for the moment can I just point my flake.nix to your fork and have it work?

**Comment by nonetrix** [comment]
> This should be pulled, for the moment can I just point my flake.nix to your fork and have it work?

That's what I did and no issues

**Comment by nonetrix** [comment]
> It‘s broken again with `hyprlang>4.2`
According to a user on #53 it might be broken again not sure

**Comment by dasehak** [comment]
> > It‘s broken again with `hyprlang>4.2`
> 
> According to a user on #53 it might be broken again not sure

yes, it's broken

**Comment by Duckonaut** [comment]
Fixed by merging #52

**Pull request closed without merging**
